[package]
name = "tokio_question"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive", "env"] }
tokio = { version = "1", features = [
    "rt",
    "rt-multi-thread",
    "macros",
    "time",
] }
